In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

db = pd.read_csv("Natural_Environment_Conditions_2010.csv", sep=",")

avg_num_trees = db["# Street Trees"].mean()
avg_num_parkSpace = db["Park Space (acres/1000 pers.)"].mean()


mask = (db["# Street Trees"] > avg_num_trees  ) & (db["Park Space (acres/1000 pers.)"] > avg_num_parkSpace - 20 )
maskedDB = db[mask] 

top30_env = maskedDB[["Neighborhood", "# Street Trees", "Park Space (acres/1000 pers.)" ]].sort_values("# Street Trees", ascending = False)
top30_env

                 Neighborhood  # Street Trees  Park Space (acres/1000 pers.)
76        Squirrel Hill South            2263                      45.306618
75        Squirrel Hill North            1846                       2.309601
67                  Shadyside            1601                       1.225656
71           South Side Flats            1337                       3.178111
62               Point Breeze            1092                      10.307432
9                  Bloomfield            1035                       0.562544
39              Highland Park            1012                      54.844722
13                  Brookline             813                       4.604359
78            Stanton Heights             730                       3.027385
12           Brighton Heights             729                       4.587415
52           Mount Washington             724                      12.664735
28               East Liberty             703                       3.204294
16  Central Business District             694                       8.048774
55              North Oakland             635                       1.379395
48                 Manchester             610                       3.309390
15                    Carrick             595                       3.656877
18          Central Northside             559                       0.299692
36                 Greenfield             540                       1.315191
7                   Beechview             512                       2.504389
5                  Banksville             506                       4.115347
38                  Hazelwood             491                       5.668751
43                  Knoxville             464                       0.013611
63         Point Breeze North             442                       5.856378
23           Crawford-Roberts             417                       2.357270
60                Perry North             402                      63.860741
56                North Shore             400                      35.412541
27                 East Hills             379                       4.249606
17      Central Lawrenceville             377                       1.344935
68                   Sheraden             365                      11.319117

# Conclusion

#### The above code reads in a csv file then calculates the average of two columns ( street trees and park space per 1000 people ). After that, a mask is applied to the data to filter out neighborhoods that don't meet the threshholds of the averages. Then, those two coloumns are selected and are sorted by the number of street trees.